<a href="https://colab.research.google.com/github/mottupally/Task_Aiml/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
s = pd.Series([1,2,3,4,5,6,7])
print(s)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [ ]:
print(s.describe())

count    7.000000
mean     4.000000
std      2.160247
min      1.000000
25%      2.500000
50%      4.000000
75%      5.500000
max      7.000000
dtype: float64

In [ ]:
print(s.mean())
print(s.std())
print(s.min())
print(s.max())

4.0
2.160246899469287
1
7

In [ ]:
mapping = s.map(lambda x :x*2)
print(mapping)
print(s)

0     2
1     4
2     6
3     8
4    10
5    12
6    14
dtype: int64
0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [ ]:
applies = s.apply(lambda x : x ** 2)
print(applies)
print(s)

0     1
1     4
2     9
3    16
4    25
5    36
6    49
dtype: int64
0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [ ]:
s1 = pd.Series([4,7,54,23,92,41])
sorted = s1.sort_values()
print(sorted)

0     4
1     7
3    23
5    41
2    54
4    92
dtype: int64

In [ ]:
dropped = s.drop(1)
print(dropped)
print(s)

0    1
2    3
3    4
4    5
5    6
6    7
dtype: int64
0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [ ]:
s2 = pd.Series([2,4,6,np.nan,7,0])
print(s2.isnull())

0    False
1    False
2    False
3     True
4    False
5    False
dtype: bool

In [ ]:
print(s2.notnull())

0     True
1     True
2     True
3    False
4     True
5     True
dtype: bool

In [ ]:
print(s2.fillna(0))

0    2.0
1    4.0
2    6.0
3    0.0
4    7.0
5    0.0
dtype: float64

In [ ]:
s3 = pd.Series([4,7,3,None,8,2,np.nan])
print(s3)
print(s3.dropna())

0    4.0
1    7.0
2    3.0
3    NaN
4    8.0
5    2.0
6    NaN
dtype: float64
0    4.0
1    7.0
2    3.0
4    8.0
5    2.0
dtype: float64

In [ ]:
print(s.iloc[2])
print(s.iloc[-2])

3
6

In [ ]:
print(s.loc[2])
print(s.loc[1:2])

3
1    2
2    3
dtype: int64

In [ ]:
greater_num = s[s<=5]
print(greater_num)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
print(s.sum())

28

In [ ]:
print(s.cumsum())

0     1
1     3
2     6
3    10
4    15
5    21
6    28
dtype: int64

In [ ]:
print(s.aggregate(['sum','std','mean']))

sum     28.000000
std      2.160247
mean     4.000000
dtype: float64

In [ ]:
data = {
    "name" : ['sruthi','hema','ashok','rohith','venkatesh','mohith','Azmath',
              'Ravi','priya','Nikhitha','shila','bhoomika','sushma'],
    "age" : [23,32,21,15,65,51,22,43,25,89,99,20,19],
    "branch" : ['CSE','ECE','AIML','CSM','DS','IOT','CS','Mech','Civil','EEE','IT',
                'AIDS','FD'],
    "Address" : ['Hyd','panjab','Assam','Bihar','JK','chennai','Bglr','kerala','pune',
                 'Mumbai','Goa','Pondi','Coimb']
}
df = pd.DataFrame(data)
df

         name  age branch  Address
0      sruthi   23    CSE      Hyd
1        hema   32    ECE   panjab
2       ashok   21   AIML    Assam
3      rohith   15    CSM    Bihar
4   venkatesh   65     DS       JK
5      mohith   51    IOT  chennai
6      Azmath   22     CS     Bglr
7        Ravi   43   Mech   kerala
8       priya   25  Civil     pune
9    Nikhitha   89    EEE   Mumbai
10      shila   99     IT      Goa
11   bhoomika   20   AIDS    Pondi
12     sushma   19     FD    Coimb

In [ ]:
df.head(7)

        name  age branch  Address
0     sruthi   23    CSE      Hyd
1       hema   32    ECE   panjab
2      ashok   21   AIML    Assam
3     rohith   15    CSM    Bihar
4  venkatesh   65     DS       JK
5     mohith   51    IOT  chennai
6     Azmath   22     CS     Bglr

In [ ]:
df.tail(7)

        name  age branch Address
6     Azmath   22     CS    Bglr
7       Ravi   43   Mech  kerala
8      priya   25  Civil    pune
9   Nikhitha   89    EEE  Mumbai
10     shila   99     IT     Goa
11  bhoomika   20   AIDS   Pondi
12    sushma   19     FD   Coimb

In [ ]:
print(df.describe())

             age
count  13.000000
mean   40.307692
std    27.935594
min    15.000000
25%    21.000000
50%    25.000000
75%    51.000000
max    99.000000

In [ ]:
import pandas as pd
import numpy as np
# Step 2: Upload CSV file from your system
from google.colab import files
uploaded = files.upload()

# Step 3: Read the uploaded CSV file
# Replace 'your_file.csv' with actual uploaded file name
df = pd.read_csv(list(uploaded.keys())[0])

# Display first 5 rows
print("First 5 rows:")
print(df.head())

# Step 4: Basic Information
print("\nDataset Info:")
print(df.info())

print("\nSummary Statistics:")
print(df.describe())

# Step 5: Handling Missing Values
print("\nMissing Values:")
print(df.isnull().sum())

# Fill missing values with 0 (example)
df = df.fillna(0)

# Step 6: Filtering Data (example)
# Filter days with high temperature (>30)
if 'temperature' in df.columns:
    filtered_df = df[df['temperature'] > 10]
    print("\nFiltered Data (Temperature > 30):")
    print(filtered_df)

# Step 7: Adding New Column
# Example: classify weather based on temperature
if 'temperature' in df.columns:
    df['weather_type'] = df['temperature'].apply(
        lambda x: 'Hot' if x >= 30 else 'Normal'
    )

# Step 8: GroupBy Example
# Average temperature based on weather condition
if 'weather_condition' in df.columns:
    group_data = df.groupby('weather_condition')['temperature'].mean()
    print("\nAverage Temperature by Weather Condition:")
    print(group_data)

# Step 9: Save Modified File
df.to_csv("processed_data.csv", index=False)

# Step 10: Download the processed file
from google.colab import files
files.download("processed_data.csv")